#!/bin/bash

echo "Copying files to desktop..."

cp "./bootstrap"        "${HOME}/Desktop/"
cp "./mount-shares"     "${HOME}/Desktop/"
cp "./reverse-flash"    "${HOME}/Desktop/"
cp "./Admin Notes.md"   "${HOME}/Desktop/"
cp "./Todo.md"          "${HOME}/Desktop/"
