#!/bin/bash

# Exit on error
set -e

###########################################
#                                         #
#          EXAMPLE CONFIGURATION          #
#                                         #
###########################################

# Mounts the share named foo to /tmp/foo:
# /usr/bin/vmhgfs-fuse .host:/foo /tmp/foo -o subtype=vmhgfs-fuse,allow_other

# source: https://docs.vmware.com/en/VMware-Workstation-Pro/17/com.vmware.ws.using.doc/GUID-AB5C80FE-9B8A-4899-8186-3DB8201B1758.html

##############################################
#                                            #
#          BEGIN USER CONFIGURATION          #
#                                            #
##############################################

# To Linux

dev="/To Linux"
mount="${HOME}/Desktop/To Linux"

mkdir -p "$mount" && /usr/bin/vmhgfs-fuse .host:"$dev" "$mount" -o subtype=vmhgfs-fuse,allow_other

# To Windows

dev="/To Windows"
mount="${HOME}/Desktop/To Windows"

mkdir -p "$mount" && /usr/bin/vmhgfs-fuse .host:"$dev" "$mount" -o subtype=vmhgfs-fuse,allow_other
