#!/bin/bash

LINUX_FILES="${HOME}/Desktop/_Linux Files"

echo "Copying files FROM desktop..."

cp "${HOME}/Desktop/bootstrap"     "${LINUX_FILES}/"
cp "${HOME}/Desktop/mount-shares"  "${LINUX_FILES}/"
cp "${HOME}/Desktop/reverse-flash" "${LINUX_FILES}/"
