#!/bin/bash

# Exit on error
set -e

FILES_SUBVOL="${HOME}/Desktop/@files"

GIT="${FILES_SUBVOL}/git"

DIR="${GIT}/bootstrap"

echo "Copying files FROM desktop..."

cp "${HOME}/Desktop/bootstrap"              "${DIR}/"
cp "${HOME}/Desktop/mount-shares"           "${DIR}/"
cp "${HOME}/Desktop/reverse-flash"          "${DIR}/"
cp "${HOME}/Desktop/README.AdminNotes.md"   "${DIR}/"
cp "${HOME}/Desktop/Todo.md"                "${DIR}/"

##########################
#                        #
#     BEGIN GIT SYNC     #
#                        #
##########################

cd "$DIR"

git add .
git commit -m 'reverse-flash'
git push
